// One-time optimizer for the "Our Moments" gallery.
//
// The source photos in public/moments*.jpg are full-resolution Canon EOS R6
// Lightroom exports (~3648x5472, ~7.6 MB each, 152 MB total) but are displayed
// at <=320px (featured) / 112px (thumbnails) on a phone-width column. This
// script downscales them, strips EXIF, and re-encodes to WebP — cutting the
// gallery payload ~97% — while keeping the same .jpg filenames so no <Image>
// src paths change (browsers and Next's optimizer sniff content, not extension).
//
// It also emits a blur map: a tiny base64 WebP per image, written to
// src/app/(invite)/_components/momentsBlur.ts for `placeholder="blur"`.
//
// Re-runnable: reads originals from a backup dir if provided (SRC_DIR env),
// otherwise from public/ in place. Run: `pnpm run optimize:moments`.

import { readdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Where to read originals from (defaults to public/, overridable for re-runs
// against a pristine backup). Output always goes to public/.
const SRC_DIR = process.env.SRC_DIR
  ? process.env.SRC_DIR
  : join(ROOT, "public");
const OUT_DIR = join(ROOT, "public");
const BLUR_MODULE = join(
  ROOT,
  "src",
  "app",
  "(invite)",
  "_components",
  "momentsBlur.ts",
);

const MAX_EDGE = 1080; // long-edge cap: 2x+ headroom over the 320px display
const QUALITY = 80; // WebP quality; lands each file ~150-250 KB
const BLUR_WIDTH = 16; // tiny blur-up placeholder width

const MOMENT_RE = /^moments(\d+)\.jpg$/i;

function fmtKB(bytes) {
  return `${(bytes / 1024).toFixed(0)} KB`;
}

async function run() {
  const files = (await readdir(SRC_DIR))
    .map((name) => {
      const m = name.match(MOMENT_RE);
      return m ? { name, index: Number(m[1]) } : null;
    })
    .filter(Boolean)
    .sort((a, b) => a.index - b.index);

  if (files.length === 0) {
    console.error(`No moments*.jpg found in ${SRC_DIR}`);
    process.exit(1);
  }

  console.log(`Optimizing ${files.length} images from ${SRC_DIR}\n`);

  // blurByIndex[n] = data URL for moments(n+1).jpg, kept in filename order.
  const blurByIndex = [];
  let totalOut = 0;

  for (const { name, index } of files) {
    const inputPath = join(SRC_DIR, name);
    const outputPath = join(OUT_DIR, name);

    // Decode once; strip metadata (no .withMetadata()), resize, encode WebP.
    const base = sharp(inputPath).rotate(); // honor EXIF orientation before strip

    const optimized = await base
      .clone()
      .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: "inside", withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toBuffer();

    const blur = await base
      .clone()
      .resize({ width: BLUR_WIDTH, fit: "inside" })
      .webp({ quality: 40 })
      .toBuffer();

    await writeFile(outputPath, optimized);
    blurByIndex[index - 1] = `data:image/webp;base64,${blur.toString("base64")}`;
    totalOut += optimized.length;

    console.log(`  ${name.padEnd(15)} -> ${fmtKB(optimized.length)}`);
  }

  // Emit the blur module. Any gaps (missing index) become empty strings, but
  // the current set is 1..20 contiguous.
  const entries = [];
  for (let i = 0; i < blurByIndex.length; i++) {
    entries.push(`  ${JSON.stringify(blurByIndex[i] ?? "")},`);
  }
  const module = `// AUTO-GENERATED by scripts/optimize-moments.mjs — do not edit by hand.
// Tiny base64 WebP blur-up placeholders for the "Our Moments" gallery,
// one per public/moments{n}.jpg (index n-1). Regenerate: pnpm run optimize:moments
export const MOMENTS_BLUR: string[] = [
${entries.join("\n")}
];
`;
  await writeFile(BLUR_MODULE, module);

  console.log(`\nTotal optimized: ${fmtKB(totalOut)} across ${files.length} images`);
  console.log(`Blur module: ${BLUR_MODULE}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
